# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 06:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=120)),
                ('year', models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1990)])),
                ('price', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('odometer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dealer', models.BooleanField()),
                ('posted_at', models.DateTimeField(db_index=True)),
                ('post_url', models.URLField(db_index=True, unique=True)),
                ('title_status', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('drive', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel', models.CharField(blank=True, max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('condition', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cylinders', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(blank=True, null=True)),
                ('predict_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('predicted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_web_hook', models.URLField(blank=True, db_index=True, max_length=2048, null=True)),
                ('min_year', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990)])),
                ('max_year', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990)])),
                ('min_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('title_status', models.CharField(blank=True, max_length=20, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('predict_model', models.CharField(blank=True, max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Make'),
        ),
    ]
