# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', related_query_name='model', to='api.Make'),
            preserve_default=False,
        ),
    ]
