# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171025_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
