# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171025_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='slack_web_hook',
            field=models.URLField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
