version: "3.2"
services:
  mongodb:
    image: mongo:3.4.4
    volumes:
      - "mongo_data:/data/db"
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      overlay:
  redis:
    image: redis
    volumes:
      - "redis_data:/data"
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      overlay:
  mysql:
    image: mysql:5.7.20
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd

volumes:
  mongo_data:
  redis_data:
  mysql_data:

networks:
  overlay:
